# Generated by Django 3.2.9 on 2021-12-09 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 18, 19, 28, 744554)),
        ),
    ]
