# Generated by Django 3.2.9 on 2021-11-08 19:34

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('about_info', models.CharField(max_length=300)),
                ('icon_image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('background_image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('applicant_blog', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='smooth_auth.smoothuser')),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('sub_name', models.CharField(max_length=100)),
                ('about_info', models.CharField(max_length=300)),
                ('icon_image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('background_image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('business_website', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='smooth_auth.smoothuser')),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Business Profile',
            },
        ),
        migrations.AddField(
            model_name='smoothuser',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
