# Generated by Django 3.2.9 on 2021-11-08 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0002_auto_20211108_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='applicant_blog',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_website',
            field=models.URLField(blank=True),
        ),
    ]
