# Generated by Django 3.2.9 on 2021-11-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0003_auto_20211108_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmoothSession',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='smooth_auth.smoothuser')),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
