# Generated by Django 3.2.9 on 2021-11-12 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0006_auto_20211112_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 12, 7, 53, 786868)),
        ),
        migrations.AlterField(
            model_name='smoothsession',
            name='set_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 12, 7, 53, 786868)),
        ),
    ]
