# Generated by Django 3.2.9 on 2021-11-12 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0007_auto_20211112_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 12, 23, 42, 795010)),
        ),
        migrations.AlterField(
            model_name='smoothsession',
            name='set_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 12, 23, 42, 795010)),
        ),
    ]
