# Generated by Django 3.2.9 on 2021-11-12 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0008_auto_20211112_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='smoothsession',
            name='set_data',
        ),
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 13, 46, 3, 662064)),
        ),
    ]
