# Generated by Django 3.2.9 on 2021-11-12 12:05

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0010_auto_20211112_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='about_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 14, 5, 2, 810612)),
        ),
    ]
