# Generated by Django 3.2.9 on 2021-11-15 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0012_auto_20211112_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 11, 13, 5, 672559)),
        ),
    ]
