# Generated by Django 3.2.9 on 2021-12-09 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0022_alter_smoothsession_expiry_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='preferred_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 14, 52, 55, 320344, tzinfo=utc)),
        ),
    ]
