# Generated by Django 3.2.9 on 2021-12-09 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0023_auto_20211209_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 15, 16, 1, 313796, tzinfo=utc)),
        ),
    ]
