# Generated by Django 3.2.9 on 2021-12-13 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_auth', '0026_alter_smoothsession_expiry_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smoothsession',
            name='expiry_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 18, 13, 17, 72655, tzinfo=utc)),
        ),
    ]
